### ISSUE TITLE
Version information in git dependencies incompatible with other crates

### ISSUE THREAD

**Issue by vhdirk** [gtk-rs/pangocairo#19]
When trying to combine this crate with e.g. https://github.com/sdroege/gobject-subclass, you get conflicts for the ```-sys``` crates since in this one, you're specifying actual versions, unlike the other crates from gtk-rs.

**Comment by GuillaumeGomez** [comment]
Are you talking about the published version or the master branch?

**Comment by vhdirk** [comment]
About the master branch. Is there any consensus between the gtk-rs developers on how dependencies on git versions are specified?

**Comment by GuillaumeGomez** [comment]
Not as far as I know.

cc @sdroege

**Comment by sdroege** [comment]
In git master we never specify versions and only git dependencies, in releases we don't specify git but versions. That's how it usually works.

Also pangocairo has to be updated to bitflags 1.0 :)

**Comment by sdroege** [comment]
This is done now

**Comment by GuillaumeGomez** [comment]
Closing then.
