### ISSUE TITLE
PangoCairoFcFontMap

### ISSUE THREAD

**Issue by velyan** [gtk-rs/pangocairo#56]
hey 👋 

I'm trying to use https://github.com/servo/rust-fontconfig with pangocairo. I use `pangocairo::FontMap::new_for_font_type(cairo::FontType::FontTypeFt)` to create a new `PangoCairoFcFontMap`. And I need to use some functions from this interface, but no rust wrappers exist atm. 

What's the best way to get them exposed? I am interested in this method specifically - https://github.com/GNOME/pango/blob/master/pango/pangofc-fontmap.c#L1928

**Comment by EPashkin** [comment]
IMHO `pango_cairo_font_map_new_for_font_type` returns `PangoCairoFontMap` not `PangoCairoFcFontMap`.
Seems you need create new crate pangofc. It maybe can generated from PangoFc-1.0.gir

**Comment by EPashkin** [comment]
Bad that ubuntu's package don't contains PangoFc-1.0.gir

**Comment by velyan** [comment]
Oh 😞what needs to be done in this case?

**Comment by EPashkin** [comment]
See https://gtk-rs.org/docs-src/tutorial/gir_tutorial

**Comment by velyan** [comment]
Thanks, and do I need to generate a `.gir` file too? Since it's not available [here](https://github.com/gtk-rs/gir-files)?

**Comment by EPashkin** [comment]
IMHO better use file from [debian](https://packages.debian.org/search?suite=experimental&arch=i386&mode=path&searchon=contents&keywords=gir&sort_by=pkg).
You can make fork of https://github.com/gtk-rs/gir-files and add PangoFc-1.0.gir there

**Comment by velyan** [comment]
Hey @EPashkin - created a [PR](https://github.com/gtk-rs/gir-files/pull/41)

**Comment by velyan** [comment]
I'm now trying to generate a PangoFc crate from the `.gir` file. I'm following the tutorial and I'm getting the following error when I run `gir -m sys -d ../../gir-files/`: 

`GirXml: ../../gir-files/PangoFc-1.0.gir at line 404:10: <type> element is missing a name attribute`

I'm assuming the Gir file needs fixing, but now sure how. Any help much appreciated 🙏

**Comment by GuillaumeGomez** [comment]
I guess it can be closed then? If you have issues using gir, don't hesitate to ask!
