### ISSUE TITLE
Allow clearing default font_map

### ISSUE THREAD

**Issue by cthorner** [gtk-rs/pangocairo#60]
I might just be doing this wrong, but I would like to clear the default font_map so that it can be reimported next time it is needed and pick up any new fonts that have been added. I see that I can set a new font_map with set_default, but it expects a font_map reference as input. See here:

https://github.com/gtk-rs/pangocairo/blob/master/src/auto/font_map.rs#L42

I'm new to rust, so I might be missing some way of getting it to work with the current code by casting ptr.null_mut() to a font_map. Seems very un-rusty. Would it be possible to allow this? Either by modifying set_default, or, maybe better, by adding a clear_default() method.

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/pangocairo/pull/62

**Comment by cthorner** [comment]
Ok, thanks! I'll try that out.

Before this I ended up calling the sys library directly with a null ptr. I also tried exposing every conceivable clear cache like functionality in pango, with no luck so far. For future reference, here is the current conversation:

https://gitlab.gnome.org/GNOME/pango/issues/443

Regardless the nullable set_default is a great addition. Thanks again for adding this.
